export enum VALIDATE_TYPE {
  REQUIRED = "REQUIRED",
  LENGTH = "LENGTH",
  FORMAT = "FORMAT",
  NO_SPEACIAL_CHARACTERS = "NO_SPEACIAL_CHARACTERS",
  DATA_TYPE = "DATA_TYPE",
  IN_RANGE = "IN_RANGE",
  DUPLICATE = "DUPLICATE",
}

export enum FORMAT_VALIDATE_TYPE {
  EMAIL = "EMAIL",
  PHONE_NUMBER = "PHONE_NUMBER",
  URL = "URL",
  STRONG_PASSWORD = "STRONG_PASSWORD",
  TIME = "TIME",
}

export enum DATA_TYPE_VALIDATE_TYPE {
  INTEGER = "INTEGER",
  NUMBER = "NUMBER",
  STRING = "STRING",
  BOOLEAN = "BOOLEAN",
}

export enum IN_RANGE_VALIDATE_TYPE {
  NUMBER = "NUMBER",
  DATE = "DATE",
}

export enum INPUT_FORMAT_TYPE {
  UPPERCASE = "UPPERCASE",
  ONLY_NUMBER = "ONLY_NUMBER",
  NUMBER_VALUE = "NUMBER_VALUE",
  NO_SPACE = "NO_SPACE",
  UPPERCASE_AND_NO_SPACE = "UPPERCASE_AND_NO_SPACE",
  ONLY_NUMBER_AND_NO_SPACE = "ONLY_NUMBER_AND_NO_SPACE",
}
