import { createStyles, makeStyles } from "@mui/styles";
import { Theme } from "@mui/material";
export const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {},
    common_button3: {
      width: 138,
      display: "flex",

      padding: "8px 16px",
      backgroundColor: "#a6e6c2",
      border: "1px solid #a6e6c2",
      color: "#04A857",
      textAlign: "center",
      textDecoration: "none",
      fontSize: "14px",
      fontWeight: 600,
      cursor: "pointer",
      borderRadius: "4px",
      "&:hover": {
        backgroundColor: "#a6e6c2",
        borderColor: "#a6e6c2",
      },
      "& .MuiLoadingButton-loadingIndicator": {
        top: "50%",
        left: "16%",
        transform: "translate(-50%, -50%)",
      },
    },
    common_button4: {
      width: 138,
      display: "flex",

      padding: "8px 16px",
      backgroundColor: "#FFE2DF",
      border: "1px solid #FFE2DF",
      color: "#E6544F",
      textAlign: "center",
      textDecoration: "none",
      fontSize: "14px",
      fontWeight: 600,
      cursor: "pointer",
      borderRadius: "4px",
      "&:hover": {
        backgroundColor: "#FFE2DF",
        borderColor: "#FFE2DF",
      },
      "& .MuiLoadingButton-loadingIndicator": {
        top: "50%",
        left: "16%",
        transform: "translate(-50%, -50%)",
      },
    },
    common_button5: {
      width: 138,
      display: "flex",

      padding: "8px 16px",
      backgroundColor: "#D1E7FF",
      border: "1px solid #D1E7FF",
      color: "#00A3FF",
      textAlign: "center",
      textDecoration: "none",
      fontSize: "14px",
      fontWeight: 600,
      cursor: "pointer",
      borderRadius: "4px",
      "&:hover": {
        backgroundColor: "#D1E7FF",
        borderColor: "#D1E7FF",
      },
      "& .MuiLoadingButton-loadingIndicator": {
        top: "50%",
        left: "16%",
        transform: "translate(-50%, -50%)",
      },
    },
    common_button6: {
      width: 158,
      display: "flex",
      padding: "8px 16px",
      backgroundColor: "#D1E7FF",
      border: "1px solid #D1E7FF",
      color: "#00A3FF",
      textAlign: "center",
      textDecoration: "none",
      fontSize: "14px",
      fontWeight: 600,
      cursor: "pointer",
      borderRadius: "4px",
      "&:hover": {
        backgroundColor: "#D1E7FF",
        borderColor: "#D1E7FF",
      },
      "& .MuiLoadingButton-loadingIndicator": {
        top: "50%",
        left: "16%",
        transform: "translate(-50%, -50%)",
      },
    },
    common_button3_small: {
      width: 85,
      display: "flex",
      padding: "4px 4px",
      backgroundColor: "#a6e6c2",
      border: "1px solid #a6e6c2",
      color: "#04A857",
      textAlign: "center",
      textDecoration: "none",
      fontSize: "10px",
      fontWeight: 600,
      cursor: "pointer",
      borderRadius: "4px",
      "&:hover": {
        backgroundColor: "#a6e6c2",
        borderColor: "#a6e6c2",
      },
      "& .MuiLoadingButton-loadingIndicator": {
        top: "50%",
        left: "16%",
        transform: "translate(-50%, -50%)",
      },
    },
    common_button4_small: {
      width: 85,
      display: "flex",
      padding: "4px 4px",
      backgroundColor: "#FFE2DF",
      border: "1px solid #FFE2DF",
      color: "#E6544F",
      textAlign: "center",
      textDecoration: "none",
      fontSize: "10px",
      fontWeight: 600,
      cursor: "pointer",
      borderRadius: "4px",
      "&:hover": {
        backgroundColor: "#FFE2DF",
        borderColor: "#FFE2DF",
      },
      "& .MuiLoadingButton-loadingIndicator": {
        top: "50%",
        left: "16%",
        transform: "translate(-50%, -50%)",
      },
    },
    common_button5_small: {
      width: 85,
      display: "flex",
      padding: "4px 4px",
      backgroundColor: "#D1E7FF",
      border: "1px solid #D1E7FF",
      color: "#00A3FF",
      textAlign: "center",
      textDecoration: "none",
      fontSize: "10px",
      fontWeight: 600,
      cursor: "pointer",
      borderRadius: "4px",
      "&:hover": {
        backgroundColor: "#D1E7FF",
        borderColor: "#D1E7FF",
      },
      "& .MuiLoadingButton-loadingIndicator": {
        top: "50%",
        left: "16%",
        transform: "translate(-50%, -50%)",
      },
      ".css-1d6wzja-MuiButton-startIcon": {
        marginRight: "4px",
      }
    },
  }),
);
